FROM bellsoft/liberica-openjdk-debian:17.0.11-cds
LABEL maintainer="gefangshuai <gefangshuai@163.com>"

#设置字符集
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

ADD ./libs/msyh.ttc /usr/share/fonts/
ADD ./libs/msyhbd.ttc /usr/share/fonts/
ADD ./libs/msyhl.ttc /usr/share/fonts/
ADD ./libs/simsun.ttc /usr/share/fonts/
ADD ./zhFonts/ /usr/share/fonts/zhFonts/
